---
- name: Be sure that ntpd is installed
  yum: name=ntp state=installed

- name: Set timezone
  file: state=link path=/etc/localtime src=/usr/share/zoneinfo/Asia/Tokyo force=yes

- name: Configure ntpd
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntpd
