---
- name: Add yum repository for Slurm
  yum_repository:
    name: bintray-shimojo-lab-slurm
    description: Shimojo Lab's Unofficial Build of Slurm
    baseurl: https://dl.bintray.com/shimojo-lab/slurm

- name: Install Slurm packages
  yum: name={{ item }} disable_gpg_check=yes
  with_items:
    - slurm
    - slurm-plugins
    - slurm-munge
    - slurm-perlapi
    - slurm-contribs
    - mailx

- name: Copy slurm configuration file
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
  notify: Reload slurm config

- name: Copy slurm cgroup configuration file
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf

- name: Start slumctld
  service: name=slurmctld state=started enabled=yes
  when: "'master' in group_names"

- name: start slurmd
  service: name=slurmd state=started enabled=yes
  when: "'slave' in group_names"
