---
- name: Forbid root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin (yes|no)"
    line: "PermitRootLogin no"
  notify: Restart sshd

- name: Disable DNS reverse lookup
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?UseDNS (yes|no)"
    line: "UseDNS no"
  notify: Restart sshd

- name: Disable host key checking
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"

- include: master.yml
  when: "'master' in group_names"
