---
- name: Forbid root to access via ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin (yes|no)"
    line: "PermitRootLogin no"
  notify: restart sshd

- include: master.yml
  when: "'master' in group_names"

- include: slave.yml
  when: "'slave' in group_names"
