---
- name: Create ssh key pair for current user
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes

- name: Read generated public key
  command: cat /home/{{ ansible_user }}/.ssh/id_rsa.pub
  register: my_pubkey
  changed_when: false

- name: Add public key to authorized keys
  authorized_key:
    user: vagrant
    state: present
    key: "{{ my_pubkey.stdout }}"
