---
- name: Forbid root to access via ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin (yes|no)"
    line: "PermitRootLogin no"
  notify: restart sshd

- name: Enable SSH keysign
  lineinfile:
    dest: /etc/ssh/ssh_config
    state: present
    line: "EnableSSHKeysign yes"

- name: Enable hostbased authentication
  lineinfile:
    dest: /etc/ssh/ssh_config
    state: present
    line: "HostbasedAuthentication yes"

- name: Check if host key pair exists on master
  stat: path=/etc/ssh/ssh_host_rsa_key.pub
  register: host_key

- name: Generate host key pair on master if it doesn't exist
  command: ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
  when:
    - host_key.stat.exists == False
