---
- name: Permit hostbased authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#?HostbasedAuthentication (yes|no)"
    line: "HostbasedAuthentication yes"
    backup: yes
  notify: restart sshd

- name: Configure shosts.equiv
  template: src=shosts.equiv.j2 dest=/etc/ssh/shosts.equiv

- name: Fetch host key from master
  command: "ssh-keyscan -t rsa {{ master_hostname }}"
  register: master_host_key
  changed_when: false
  always_run: yes

- name: Save host key to ssh_known_hosts
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: yes
    state: present
    line: "{{ master_host_key.stdout }}"
