---

- name: Install reqired yum packages
  action: yum name={{ item }}
  with_items:
    - rpcbind
    - nfs-utils

- include: master.yml
  when: "'master' in group_names"

- include: slave.yml
  when: "'slave' in group_names"
