- name: Configure exports
  lineinfile:
    dest: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - "/home {{ management_network }}(rw,no_root_squash,no_subtree_check)"

- name: Enable some services for nfs server
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nfs-server
    - rpcbind
