- name: Enable services for nfs client
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind

- name: Mount /home directories on nfs server
  command: mount -t nfs {{ master_hostname }}:/home /home

- name: Configure fstab
  lineinfile:
    dest: /etc/fstab
    state: present
    backup: yes
    line: "{{ item }}"
  with_items:
    - "{{ master_hostname }}:/home /home nfs rw,relatime,rsize=131072,wsize=131072,hard 0 0"
