- name: Enable some services for nfs client
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-lock
    - nfs-mountd

- name: Mount /home directories on nfs server
  command: mount -t nfs {{ nfs_server }}:/home /home

- name: Mount /sdnjms directories on nfs server
  command: mount -t nfs {{ nfs_server }}:/sdnjms /sdnjms

- name: Configure fstab
  lineinfile:
    dest: /etc/fstab
    state: present
    backup: yes
    line: "{{ item }}"
  with_items:
    - "{{ nfs_server }}:/home /home nfs rw,vers=3,addr={{ nfs_server_ip }} 0 0"
    - "{{ nfs_server }}:/sdnjms /sdnjms nfs rw,vers=3,addr={{ nfs_server_ip }} 0 0"
