---
- name: Install rpcbind
  yum: name={{ item }} state=installed
  with_items:
    - rpcbind

- name: Enable rpcbind
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind

- name: Check current NIS domain name
  command: ypdomainname
  register: current_nis_domain
  changed_when: false
  always_run: yes
  failed_when: false

- name: Configure NIS domain name
  command: ypdomainname {{ nis_domain }}
  when: current_nis_domain.stdout != nis_domain

- name: Make NIS domain name permanent
  lineinfile:
    dest: /etc/sysconfig/network
    state: present
    line: "NISDOMAIN={{ nis_domain }}"

- include: master.yml
  when: "'master' in group_names"

- include: slave.yml
  when: "'slave' in group_names"
