- name: Install NIS server
  yum: name=ypserv state=installed

- name: Enable NIS server
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ypserv
    - ypxfrd
    - yppasswdd

- name: Update NIS database
  command: /usr/lib64/yp/ypinit -m creates="/var/yp/{{ nis_domain }}"
