- name: Install NIS client
  yum: name=ypbind state=installed

- name: Configure NIS
  command: authconfig --enablenis --nisdomain={{ nis_domain }} --nisserver={{ master_hostname }} --update

- name: Enable NIS client service
  service: name=ypbind state=started enabled=yes
