- name: Configure NIS domain name
  command: ypdomainname {{ nis_domain }}

- name: Modify network file for make NIS domain name permanent
  lineinfile:
    dest: /etc/sysconfig/network
    state: present
    line: "NISDOMAIN={{ nis_domain }}"

- name: Enable NIS service
  command: authconfig --enablenis --nisdomain={{ nis_domain }} --nisserver={{ nis_server }} --update

- name: Configure system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    state: present
    line: "session     optional      pam_mkhomedir.so skel=/etc/skel umask=077"

- name: Configure hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ nis_server_ip }} {{ nis_server }} {{ nis_server_s }}"

- name: Enable some services for NIS
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - ypbind
