---
# Setup for Network Mangement Module in SDN-enhanced JMS

- name: Upgrade all yum packages
  yum: name=* state=latest

- name: Be sure yum packages for Network Mangement Module are installed
  yum: name={{ item }} state=installed
  with_items:
    - ruby
    - irb
    - gcc
    - make
    - ruby-devel
    - rubygems
    - libpcap-devel
    - sqlite-devel
    - glib2-devel
    - perl
    - sudo
    - httpd
    - git

- name: Install trema
  gem: name=trema version=0.4.6 state=present user_install=no

- name: Copy nmm source dir to /root
  command: cp -r /root/SDN-JMS/src/nmm /root/ creates=/root/nmm

- name: Compile trema topology application
  command: make chdir=/root/nmm/apps/topology

- name: Compile trema routing switch application
  command: make chdir=/root/nmm/apps/routing_switch

- name: Copy trema start script
  command: cp /root/nmm/examples/start.sh /root/nmm/ creates=/root/nmm/start.sh

- name: Copy trema network configuration file
  command: cp /root/nmm/examples/switch.conf /root/nmm/ creates=/root/nmm/switch.conf

- name: Copy cgi script for nmm to /var/www/cgi-bin
  command: cp /root/nmm/examples/nmm.cgi /var/www/cgi-bin/ creates=/var/www/cgi-bin/nmm.cgi

- name: Configure access authority of /root dir
  file: path=/root owner=root group=root mode=0755

- name: Create database directory
  file: dest=/root/nmm/apps/routing_switch/database state=directory owner=root group=root mode=0777

- name: Copy configuration file for the routing switch to routing_switch directory
  copy: src=settings.rb dest=/root/nmm/apps/routing_switch/

- name: Run trema
  command: ./start.sh chdir=/root/nmm
