---

- name: Install yum packages
  action: yum name={{ item }}
  with_items:
    - epel-release
    - vim
    - environment-modules
    - openmpi

- name: Set hostname
  hostname: name={{ inventory_hostname }}

- name: Update hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Load OpenMPI into environment
  lineinfile:
    dest: /usr/share/Modules/init/bash
    line: "module load mpi"

- name: Force using ob1 pml
  lineinfile:
    dest: /etc/openmpi-x86_64/openmpi-mca-params.conf
    line: "pml = ob1"

- include: master.yml
  when: "'master' in group_names"

- include: slave.yml
  when: "'slave' in group_names"
